Feature/reports
itk-dev/ai-screening pull request #65
Opened 2024-11-28 07:32 UTC by martinyde

- Remove Choices lib from base theme
- Add choices.js lib and chart.js lib to custom theme
- Add reports module
- Add reports theming
- Add bubble chart

![Skærmbillede 2024-11-28 kl  08 47 50](https://github.com/user-attachments/assets/1d751d8b-334e-4f11-aa2f-50647f1ee4ee)

![Skærmbillede 2024-11-28 kl  08 48 10](https://github.com/user-attachments/assets/9d29eeff-c520-49d3-a3d8-b79bcb26f170)

![Skærmbillede 2024-11-28 kl  08 49 15](https://github.com/user-attachments/assets/68c3b34a-cee7-49f7-aa7f-401a1ae07707)

2024-11-28 09:28 UTC, rimi-itk requested changes

2024-11-28 09:28 UTC, rimi-itk commented on web/modules/custom/ai_screening_reports/src/Controller/AiScreeningReportsController.php
> +  }
We should report a “bad request” in this case:

```suggestion
    // If no project track ids could be identified from url params.
    throw new BadRequestHttpException();
```

Alternatively, we could set the message and return to the project list page.

2024-11-28 09:28 UTC, rimi-itk commented on web/modules/custom/ai_screening_reports/src/Form/CreateReport.php
> +      ->accessCheck('TRUE')
```suggestion
      ->accessCheck(TRUE)
```

2024-11-28 09:28 UTC, rimi-itk commented on web/modules/custom/ai_screening_reports/src/Form/CreateReport.php
> +    $projects = $this->nodeStorage->loadMultiple($projectIds);
Consider adding a `loadProjects` function in `ProjectHelper`. Corrupted projects should be excluded when loading.

2024-11-28 09:28 UTC, rimi-itk commented on web/modules/custom/ai_screening_reports/src/Form/CreateReport.php
> +    $form['projects'] = [
Consider renaming to `'project'` since we're selecting a single project.

2024-11-28 09:28 UTC, rimi-itk commented on web/themes/custom/itkdev/itkdev_project_theme/js/charts.js
> +        });
If I understand this code correctly, you're mapping `chartSettings['dataset']` to `datasets`:

```suggestion
      if (chart) {
        const datasets = chartSettings['dataset'].map(drupalData => {
          label: drupalData.chart.label,
          title: drupalData.chart.label,
          data: drupalData.plots,
          backgroundColor: drupalData.chart.color
        });
```

2024-11-28 09:28 UTC, rimi-itk commented on web/modules/custom/ai_screening_reports/src/Controller/AiScreeningReportsController.php
> +      $projectData = [
Consider adding and using a `loadTracks` function in `ProjectTrackHelper` to clean up the code:

``` php
    $projectTracks = $this->projectTrackHelper->loadTracks((array)$request->get('project_track_id'));
    if (!empty($projectTracks)) {
      …
      foreach ($projectTracks as $projectTrack) {
        $projectData['dataset'][$id]['chart'] = [ … ];
      }

      return [
        '#theme' => …,
        …
      ];
    }

    // Bad request
    …
```

2024-11-28 10:34 UTC, martinyde commented on web/modules/custom/ai_screening_project/src/Helper/ProjectHelper.php
> +  public function getProjectTracks(NodeInterface $project): array {
get methods are allowed in Twig, load methods are not by default. I guess we could allow it, but i'm not sure that is the proper way of handling this. Likewise i'm unsure if changing the name of the method is the best approach. Do we need something in between to translate from database to twig ?

2024-11-28 11:29 UTC, rimi-itk requested changes

2024-11-28 11:57 UTC, rimi-itk requested changes

2024-11-28 11:57 UTC, rimi-itk commented on web/modules/custom/ai_screening_reports/src/Controller/AiScreeningReportsController.php
> +      }
You're duplicating project tracks in `$projectTracks` (`$projectTracks[] = $projectTrack`) (and don't need to check that a track is a track):

```suggestion
      foreach ($projectTracks as $key => $projectTrack) {
        $projectData['dataset'][$loopCounter]['chart'] = [
          'label' => $projectTrack->getProject()->label(),
          'color' => self::COLOR_CODES[$loopCounter % count(self::COLOR_CODES)],
        ];
        $projectData['dataset'][$loopCounter]['plots'] = [
          // @todo get plots from the track.
          ['x' => 17, 'y' => 15, 'r' => 3],
        ];
        // Set a limit for the number of tracks to display.
        $loopCounter++;
        if ($loopCounter >= self::MAX_NUMBER_OF_TRACKS) {
          $this->messenger()
            ->addWarning($this->t('A maximum of @max tracks can be displayed.', ['@max' => self::MAX_NUMBER_OF_TRACKS]));
          break;
        }
      }
```

2024-11-29 12:17 UTC, rimi-itk approved these changes

2024-11-29 12:21 UTC, merged